// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lobby.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result int32

const (
	Result_REGISTER_SUCCESS Result = 0
	Result_REGISTER_FAIL    Result = 1
	Result_LOGIN_SUCCESS    Result = 2
	Result_LOGIN_FAIL       Result = 3
)

var Result_name = map[int32]string{
	0: "REGISTER_SUCCESS",
	1: "REGISTER_FAIL",
	2: "LOGIN_SUCCESS",
	3: "LOGIN_FAIL",
}
var Result_value = map[string]int32{
	"REGISTER_SUCCESS": 0,
	"REGISTER_FAIL":    1,
	"LOGIN_SUCCESS":    2,
	"LOGIN_FAIL":       3,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}
func (Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{0}
}

type Test struct {
	Test                 string   `protobuf:"bytes,2,opt,name=Test,proto3" json:"Test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{0}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

// 用户登陆协议
type UserLogin struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	LoginPW              string   `protobuf:"bytes,2,opt,name=LoginPW,proto3" json:"LoginPW,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{1}
}
func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (dst *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(dst, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserLogin) GetLoginPW() string {
	if m != nil {
		return m.LoginPW
	}
	return ""
}

// 注册协议
type UserRegister struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	LoginPW              string   `protobuf:"bytes,2,opt,name=LoginPW,proto3" json:"LoginPW,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegister) Reset()         { *m = UserRegister{} }
func (m *UserRegister) String() string { return proto.CompactTextString(m) }
func (*UserRegister) ProtoMessage()    {}
func (*UserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{2}
}
func (m *UserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegister.Unmarshal(m, b)
}
func (m *UserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegister.Marshal(b, m, deterministic)
}
func (dst *UserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegister.Merge(dst, src)
}
func (m *UserRegister) XXX_Size() int {
	return xxx_messageInfo_UserRegister.Size(m)
}
func (m *UserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegister proto.InternalMessageInfo

func (m *UserRegister) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserRegister) GetLoginPW() string {
	if m != nil {
		return m.LoginPW
	}
	return ""
}

// 消息返回协议
type UserResult struct {
	RetResult            Result   `protobuf:"varint,1,opt,name=RetResult,proto3,enum=msg.Result" json:"RetResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResult) Reset()         { *m = UserResult{} }
func (m *UserResult) String() string { return proto.CompactTextString(m) }
func (*UserResult) ProtoMessage()    {}
func (*UserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{3}
}
func (m *UserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResult.Unmarshal(m, b)
}
func (m *UserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResult.Marshal(b, m, deterministic)
}
func (dst *UserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResult.Merge(dst, src)
}
func (m *UserResult) XXX_Size() int {
	return xxx_messageInfo_UserResult.Size(m)
}
func (m *UserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserResult proto.InternalMessageInfo

func (m *UserResult) GetRetResult() Result {
	if m != nil {
		return m.RetResult
	}
	return Result_REGISTER_SUCCESS
}

// 玩家有角色的情况
type UserST struct {
	UID                  string   `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	ServerID             string   `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	RoleUID              string   `protobuf:"bytes,3,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`
	RoleName             string   `protobuf:"bytes,4,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	RoleLev              string   `protobuf:"bytes,5,opt,name=RoleLev,proto3" json:"RoleLev,omitempty"`
	Coin                 string   `protobuf:"bytes,6,opt,name=Coin,proto3" json:"Coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserST) Reset()         { *m = UserST{} }
func (m *UserST) String() string { return proto.CompactTextString(m) }
func (*UserST) ProtoMessage()    {}
func (*UserST) Descriptor() ([]byte, []int) {
	return fileDescriptor_lobby_84a34bff5960638f, []int{4}
}
func (m *UserST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserST.Unmarshal(m, b)
}
func (m *UserST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserST.Marshal(b, m, deterministic)
}
func (dst *UserST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserST.Merge(dst, src)
}
func (m *UserST) XXX_Size() int {
	return xxx_messageInfo_UserST.Size(m)
}
func (m *UserST) XXX_DiscardUnknown() {
	xxx_messageInfo_UserST.DiscardUnknown(m)
}

var xxx_messageInfo_UserST proto.InternalMessageInfo

func (m *UserST) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *UserST) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *UserST) GetRoleUID() string {
	if m != nil {
		return m.RoleUID
	}
	return ""
}

func (m *UserST) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserST) GetRoleLev() string {
	if m != nil {
		return m.RoleLev
	}
	return ""
}

func (m *UserST) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "msg.Test")
	proto.RegisterType((*UserLogin)(nil), "msg.UserLogin")
	proto.RegisterType((*UserRegister)(nil), "msg.UserRegister")
	proto.RegisterType((*UserResult)(nil), "msg.UserResult")
	proto.RegisterType((*UserST)(nil), "msg.UserST")
	proto.RegisterEnum("msg.Result", Result_name, Result_value)
}

func init() { proto.RegisterFile("lobby.proto", fileDescriptor_lobby_84a34bff5960638f) }

var fileDescriptor_lobby_84a34bff5960638f = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x4b, 0x84, 0x50,
	0x14, 0xcd, 0x71, 0xb2, 0xbc, 0x53, 0x83, 0x3d, 0x5a, 0xc8, 0xd0, 0x22, 0x5c, 0x55, 0x0b, 0x17,
	0xb5, 0x68, 0x1d, 0x8e, 0x33, 0x08, 0x32, 0xc5, 0x7b, 0x4a, 0xcb, 0x48, 0xb8, 0x88, 0xa0, 0xf3,
	0xc2, 0x67, 0x42, 0x7f, 0xa5, 0x5f, 0x1b, 0xf7, 0x3d, 0x3f, 0xf6, 0xad, 0x3c, 0xe7, 0x78, 0xcf,
	0xb9, 0x1f, 0x0f, 0x56, 0xb5, 0x2c, 0x8a, 0x9f, 0xf0, 0xab, 0x95, 0x9d, 0x64, 0x76, 0xa3, 0xca,
	0x60, 0x03, 0xcb, 0x0c, 0x55, 0xc7, 0x98, 0xf9, 0xfa, 0x8b, 0x5b, 0xeb, 0xce, 0xe5, 0x1a, 0x07,
	0x11, 0xb8, 0xb9, 0xc2, 0x36, 0x95, 0x65, 0x75, 0x64, 0x37, 0xe0, 0x6a, 0x70, 0xf8, 0x6c, 0xd0,
	0xb7, 0x74, 0xd5, 0x2c, 0x30, 0x1f, 0xce, 0x34, 0x79, 0x7b, 0x1f, 0x12, 0x46, 0x1a, 0xec, 0xe0,
	0x82, 0x42, 0x38, 0x96, 0x95, 0xea, 0xb0, 0xfd, 0x77, 0xce, 0x33, 0x80, 0xc9, 0x51, 0xdf, 0x75,
	0xc7, 0xee, 0xc1, 0xe5, 0xd8, 0x19, 0xa2, 0x53, 0xd6, 0x8f, 0xab, 0xb0, 0x51, 0x65, 0x68, 0x24,
	0x3e, 0xff, 0x0d, 0x7e, 0x2d, 0x70, 0xc8, 0x29, 0x32, 0xe6, 0x81, 0x9d, 0x27, 0xdb, 0xa1, 0x2b,
	0x41, 0xb6, 0x81, 0x73, 0x81, 0x6d, 0x8f, 0x6d, 0xb2, 0x1d, 0x1a, 0x4e, 0x9c, 0x66, 0xe1, 0xb2,
	0x46, 0x72, 0xd8, 0x66, 0x96, 0x81, 0x92, 0x8b, 0xa0, 0x5e, 0x61, 0x69, 0x5c, 0x23, 0x1f, 0x5d,
	0x29, 0xf6, 0xfe, 0xe9, 0xec, 0x4a, 0xb1, 0xa7, 0x13, 0x47, 0xb2, 0x3a, 0xfa, 0x8e, 0x39, 0x31,
	0xe1, 0x87, 0x0c, 0x9c, 0x61, 0xa3, 0x6b, 0xf0, 0x78, 0xbc, 0x4f, 0x44, 0x16, 0xf3, 0x0f, 0x91,
	0x47, 0x51, 0x2c, 0x84, 0x77, 0xc2, 0xae, 0xe0, 0x72, 0x52, 0x77, 0x2f, 0x49, 0xea, 0x59, 0x24,
	0xa5, 0xaf, 0xfb, 0xe4, 0x30, 0x55, 0x2d, 0xd8, 0x1a, 0xc0, 0x48, 0xba, 0xc4, 0x2e, 0x1c, 0xfd,
	0xc0, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x7e, 0xd2, 0xac, 0xef, 0x01, 0x00, 0x00,
}
